print("=== Achievement Tracker System ===")

alice = set(["first_kill", "level_10", "treasure_hunter", "speed_demon"])
bob = set(["first_kill", "level_10", "boss_slayer", "collector"])
charlie = set(["level_10", "treasure_hunter", "boss_slayer",
               "speed_demon", "perfectionist"])

achievements = alice.union(bob).union(charlie)
print("Player alice achievements:", alice)
print("Player bob achievements:", bob)
print("Player charlie achievements:", charlie)

print("\n=== Achievement Analytics ===")
print(f"All unique achievements: {achievements}")
total = len(achievements)
print(f"Total unique achievements: {total}")
common_all = alice.intersection(bob).intersection(charlie)
print(f"Common to all players: {common_all}")
alice_only = alice.difference(bob.union(charlie))
bob_only = bob.difference(alice.union(charlie))
charlie_only = charlie.difference(bob.union(alice))
rare = alice_only.union(bob_only).union(charlie_only)
print(f"Rare achievements (1 player): {rare}")
AvB_common = alice.intersection(bob)
print(f"Alice vs Bob common: {AvB_common}")
AvB_A_unique = alice.difference(bob)
AvB_B_unique = bob.difference(alice)
print(f"Alice unique: {AvB_A_unique}")
print(f"Bob unique: {AvB_B_unique}")
